spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpatest?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
      
        registration:
          naver:
            client-id: rnb9WIDpOu9ge9M2cKku
            client-secret: uRlYCQ_qE2
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email                    ,mobile # 'https://developers.naver.com/docs/login/profile/profile.md'의 "5. 출력 결과" 항목에 있음
            
          kakao:
            client-id: 0ec9e81052acada4b61a0e98229b431d
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
          
          google:
            client-id: 888589937494-jvbheovec18osmbv61883bjall494a6p.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        
